### ISSUE TITLE
Why sometimes the position of the card does not match the initial design?

### ISSUE THREAD

**Issue by 0xMulyadiKabel** [Ibrahimsyah/next-ts#11]

**Comment by Ibrahimsyah** [comment]
It probably caused by styled component library. Since next js is SSR, client side rendering style library such as styled component so sometimes the style couldn't be loaded. I am currently working on this issue and i will try to fix it by using this reference
https://dev.to/rsanchezp/next-js-and-styled-components-style-loading-issue-3i68

**Comment by Ibrahimsyah** [comment]
I've pushed a commit as a bugfix for this issue, please kindly check and let me know if the issue still not resolved
